import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@radix-ui/react-separator";
import { NavActions } from "@/components/nav-actions";
import React from "react";
import { AppBreadcrumbs } from "@/components/breadcrumbs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <header className="flex h-14 shrink-0 items-center gap-2">
              <div className="flex flex-1 items-center gap-2 px-3">
                <SidebarTrigger />
                <Separator
                  orientation="vertical"
                  className="mr-2 data-[orientation=vertical]:h-4"
                />
                <AppBreadcrumbs />
              </div>
              <div className="ml-auto px-3">
                <NavActions />
              </div>
            </header>
            <div className="flex flex-1 flex-col gap-4 px-4 py-10">
              <div className="bg-muted/50 mx-auto h-24 w-full max-w-3xl rounded-xl" />
              <div className="bg-muted/50 mx-auto h-full w-full max-w-3xl rounded-xl" />
            </div>
          </SidebarInset>
          {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
